### ISSUE TITLE
unit test failure python 3.6.5

### ISSUE THREAD

**Issue by sclarkson** [simonpercivall/astunparse#25]
`python setup.py test`
```
======================================================================
ERROR: test_joined_str (tests.test_unparse.UnparseTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sclarkson/astunparse/tests/common.py", line 296, in test_joined_str
    self.check_roundtrip('f"{key:4}={value!s}"')
  File "/home/sclarkson/astunparse/tests/test_unparse.py", line 19, in check_roundtrip
    ast2 = compile(code2, filename, mode, ast.PyCF_ONLY_AST)
  File "internal", line 2
    f'''{key:f'''4'''}={value!s}'''
                 ^
SyntaxError: invalid syntax

----------------------------------------------------------------------
```

This is on Arch Linux

`python --version`
`Python 3.6.5`

**Comment by eLvErDe** [comment]
Confirmed on Python 3.6.6 (Debian Buster), I'm actually wondering if this syntax isn't python >= 3.7...

**Comment by mbdevpl** [comment]
The f-strings are certainly a 3.6 syntax.

That `f'''{key:f'''4'''}={value!s}'''` should be `f'{key:f4}={value!s}'`(or something like that) instead.

I think that error might be occurring because implementation of unparsing of f-strings in astunparse is very simplistic. I think I did the first f-string unparsing implementation for argunparse. Maybe it's still around, and in such case I guess I'm the culprit here ;) We all could use a proper f-string unparser...

But why does this test pass on Travis where python version is 3.6.3 and not on 3.6.5 or 3.6.6? I have no idea...

**Comment by sclarkson** [comment]
I still get this (and one more f-string error) on Python 3.7.0

**Comment by simonpercivall** [comment]
This is now (should now) be fixed in v1.6.0. (Please reopen if I missed something.)

**Comment by eLvErDe** [comment]
Hello,

The patch still applies on 1.6.2 so I guess it is not fixed.
Btw, I have no idea how to re-open a GitHub ticket...

Regards,

**Comment by sclarkson** [comment]
Retested and v1.6.2 tests still work on Python 3.7.2.
